[build]
  command = "npm install && npm run build && wp core download --version=5.9 --path=wp"
  publish = "dist"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[context.production.environment]
  WP_HOME = "https://example.com"
  WP_SITEURL = "https://example.com/wp"

[context.deploy-preview.environment]
  WP_HOME = "https://deploy-preview-$COMMIT_REF--example.netlify.app"
  WP_SITEURL = "https://deploy-preview-$COMMIT_REF--example.netlify.app/wp"

[context.branch-deploy.environment]
  WP_HOME = "https://$BRANCH--example.netlify.app"
  WP_SITEURL = "https://$BRANCH--example.netlify.app/wp"
